"""add index to status of ImageGetLog

Revision ID: 0e1d34af93f3
Revises: 9fa33fb55bcc
Create Date: 2025-06-25 16:02:10.966365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1d34af93f3'
down_revision: Union[str, None] = '9fa33fb55bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_image_get_logs_status'), 'image_get_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_get_logs_status'), table_name='image_get_logs')
    # ### end Alembic commands ###
