"""initial migration

Revision ID: 68013aa08db9
Revises: 
Create Date: 2025-05-22 13:26:45.921536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68013aa08db9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_fudes_uuid'), 'fudes', ['uuid'], unique=False)
    op.add_column('grouped_aois', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grouped_aois', 'status')
    op.drop_index(op.f('ix_fudes_uuid'), table_name='fudes')
    # ### end Alembic commands ###
