"""initial migration

Revision ID: 6f9c49560275
Revises: 68013aa08db9
Create Date: 2025-05-23 23:59:37.171662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f9c49560275'
down_revision: Union[str, None] = '68013aa08db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grouped_aois', sa.Column('analysis_start_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grouped_aois', 'analysis_start_date')
    # ### end Alembic commands ###
