"""Convert centroid to float and add index

Revision ID: 95a148e2cfae
Revises: 
Create Date: 2025-05-06 19:20:54.044031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95a148e2cfae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fudes', 'uuid',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('fudes', 'centroid_lat',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('fudes', 'centroid_lon',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index('idx_lat', 'fudes', ['centroid_lat'], unique=False)
    op.create_index('idx_lat_lon', 'fudes', ['centroid_lat', 'centroid_lon'], unique=False)
    op.create_index('idx_lon', 'fudes', ['centroid_lon'], unique=False)
    op.alter_column('grouped_aoi_fudes', 'fude_id',
               existing_type=sa.NUMERIC(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grouped_aoi_fudes', 'fude_id',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_index('idx_lon', table_name='fudes')
    op.drop_index('idx_lat_lon', table_name='fudes')
    op.drop_index('idx_lat', table_name='fudes')
    op.alter_column('fudes', 'centroid_lon',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('fudes', 'centroid_lat',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('fudes', 'uuid',
               existing_type=sa.String(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    # ### end Alembic commands ###
