"""add status to ImageGetLog

Revision ID: beb4a20d913a
Revises: 6f9c49560275
Create Date: 2025-06-25 13:54:52.608551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb4a20d913a'
down_revision: Union[str, None] = '6f9c49560275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_get_logs', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_get_logs', 'status')
    # ### end Alembic commands ###
